### ISSUE TITLE
[Feature Request] Support multiple icon directories

### ISSUE THREAD

**Issue by voknelis** [Jevon617/unplugin-svg-component#10]
### Problem to solve
This feature would allow the usage of SVG's from various directories. 

Currently, the envisioned use-case involves storing all the SVG files within a singular folder. However, it's no longer align with my usage.

For instance, consider a scenario where we have 2 completely separated icon sources: an npm package called "my-icons" and some project folder titled "local-icons". Now, I have to either choose a singular icon source or set `iconDir: "."` plugin parameter to the project's root, which is rather an inconvenient choice.

#### 1. Modify `iconDir` parameter type
The possible solution might be changing `iconDir` parameter type to `string | string[]`, so that we can specify various folders as a source. 

#### 2. Allow multiple plugin instances
e.g. in vite's configuration allow to create multiple instances. Each instance would be responsible for its own set of icons.
```js
{
    plugins: [
        vitePluginSvgComponent({
            iconDir: path.resolve(__dirname, './node_modules/my-icons'),
            svgSpriteDomId: "svg_sprite__dom_1",
            componentName: "SvgIcon1"
            }
        }),
        vitePluginSvgComponent({
            iconDir: path.resolve(__dirname, './src/local-icons'),
            svgSpriteDomId: "svg_sprite__dom_2",
            componentName: "SvgIcon2"
            }
        })
    ]
}
```

However, the issue with this approach is to genererate d.ts file.

Please, let me know if you need any further assistance or clarification. 

Thanks, I really appreciate your work)

**Comment by Jevon617** [comment]
@voknelis Thanks for your Proposition.

I will do it as soon as possible.

**Comment by Jevon617** [comment]
@voknelis iconDir supports array at v0.7.5.

**Comment by voknelis** [comment]
@Jevon617 Thanks a lot!
