### ISSUE TITLE
安装包的时候出现警告提示

### ISSUE THREAD

**Issue by uiwo** [Jevon617/unplugin-svg-component#11]
WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

在https://github.com/vbenjs/vite-plugin-svg-icons/issues/73这个issues看到你的推荐。。。但是你的这个包安装同样会报这个错误。。。

**Comment by Jevon617** [comment]
@uiwo 这个警告是因为，依赖的svgo@2.x.x 会依赖stable这个库， 用于兼容 `Array#sort()`, 目前已经升级svgo@3.0.2, 去除了这个警告。

**Comment by uiwo** [comment]
6啊 感谢

**Comment by fan1chun** [comment]
我现在安装最新版本还是会提示
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

我在package.json 去掉插件安装就不会提示这个

**Comment by fan1chun** [comment]
> @uiwo 这个警告是因为，依赖的[svgo@2.x.x](mailto:svgo@2.x.x) 会依赖stable这个库， 用于兼容 `Array#sort()`, 目前已经升级svgo@3.0.2, 去除了这个警告。

我现在安装最新版本"unplugin-svg-component": "^0.10.3",还是会提示
