### ISSUE TITLE
找不到声明文件

### ISSUE THREAD

**Issue by Minori-ty** [Jevon617/unplugin-svg-component#13]
![image](https://github.com/Jevon617/unplugin-svg-component/assets/79521943/1ad8fe3f-8011-4945-8ea6-2b22ac12818b)
找不到模块的声明文件，已经在tsconfig.json添加"svg-component.d.ts",   "svg-component-global.d.ts"

是需要自己写这两个文件吗？写了后也失去name的类型提示

**Comment by Jevon617** [comment]
@Minori-ty 提供一个最小的可复现demo

**Comment by Minori-ty** [comment]
> @Minori-ty 提供一个最小的可复现demo

https://github.com/Minori-ty/demo.git

**Comment by Jevon617** [comment]
@Minori-ty 
![image](https://github.com/Jevon617/unplugin-svg-component/assets/25676701/1cc22ad7-08b3-4ebf-adcd-94e05d0ee396)

**Comment by Minori-ty** [comment]
> @Minori-ty ![image](https://private-user-images.githubusercontent.com/25676701/298435999-1cc22ad7-08b3-4ebf-adcd-94e05d0ee396.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTExMTksIm5iZiI6MTcwNTg5MDgxOSwicGF0aCI6Ii8yNTY3NjcwMS8yOTg0MzU5OTktMWNjMjJhZDctMDhiMy00ZWJmLWFkY2QtOTRlMDVkMGVlMzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzEwMDY0YzZlYzZlNjJlOTdhYjU5ZWJiMTNiMWQ4ZGNkZGI5ZTI3ODBlMGUzMGFhMjUwYWFlODA1ODc3MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gk7q3GyVjfMycNqtJ6HBQVWHiVbp7Ga2DdAOQf_xTSA)

好的谢谢，不过不能默认配置吗？

**Comment by Jevon617** [comment]
默认是false, 不是所有用户都是都用的ts

**Comment by Minori-ty** [comment]
> 默认是false, 不是所有用户都是都用的ts

好的，谢谢。

不过从优化的角度来说，是不是可以在插件启动的时候，就找一下本地是否有tsconfig.json文件，来判断该项目是否是ts项目，从而降低用户使用的心智负担？

**Comment by Jevon617** [comment]
有tsconfig.json不一定就是ts项目, 没有tsconfig.json不一定不是ts项目, 不能作为判断条件, 这里如果想优化, 需要考虑的case太多.

**Comment by Minori-ty** [comment]
> 有tsconfig.json不一定就是ts项目, 没有tsconfig.json不一定不是ts项目, 不能作为判断条件, 这里如果想优化, 需要考虑的case太多.

好的
