### ISSUE TITLE
deprecated dependencies

### ISSUE THREAD

**Issue by Asdreu** [Jevon617/unplugin-svg-component#14]
when I execute command `npm install unplugin-svg-component -D`，the npm show warn below.  

```shell
nodejs version >= 18

npm WARN deprecated source-map-url@0.4.1: See https: //github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https: //github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https: //github.com/ydell/resolve-url#deprecated
```

I found the reason is svg-baker. Maybe you need to replace this dependency.

**Comment by Jevon617** [comment]
Indeed, I may replace this dependency with [svg-sprite](https://www.npmjs.com/package/svg-sprite).

**Comment by Jevon617** [comment]
@Asdreu svg-baker has been replaced with svg-sprite in v0.9.0.
