### ISSUE TITLE
Cannot find module '@vue/compiler-sfc@3.x.x'.

### ISSUE THREAD

**Issue by 2815261401** [Jevon617/unplugin-svg-component#20]
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/66c07a0b-ff29-4c0f-a1ce-6b3fd70e5ab3)
throw new Error(`Cannot find module '@vue/compiler-sfc@${vueVerison.slice(-1)}.x.x'. Please install it.`);
          ^
Error: Cannot find module '@vue/compiler-sfc@3.x.x'. Please install it.
需要自己安装@vue/compiler-sfc不然报以上错误

**Comment by 2815261401** [comment]
0.8.0版本没有这个问题

**Comment by Jevon617** [comment]
@2815261401 你的安装策略是否开启了自动安装 peerDependencies?

**Comment by 2815261401** [comment]
没有,就是普通的pnpm i

**Comment by Jevon617** [comment]
@2815261401 发布了最新版本, 目前如果你的vue版本大于3.2.13 或者是 2.7.x不会提示错误, 否则就需要自己装一下 @vue/compiler-sfc.

**Comment by 2815261401** [comment]
可以了
