### ISSUE TITLE
icon 前缀配置和使用时不匹配

### ISSUE THREAD

**Issue by OneYonder** [Jevon617/unplugin-svg-component#21]
vue版本3.4.21
插件版本0.10.0
当我在配置文件配置了前缀的时候：
![image](https://github.com/Jevon617/unplugin-svg-component/assets/168751396/56073770-10fa-4a57-b5bf-ea4702de3d89)
svg组件使用的时候不用加 name 前缀 不加 icon-
![image](https://github.com/Jevon617/unplugin-svg-component/assets/168751396/2c3e94ed-1e1e-4914-90ff-25218de65905)
正常显示，
![image](https://github.com/Jevon617/unplugin-svg-component/assets/168751396/06684a48-62cd-46a9-8562-8d100e4ebd93)
。

加了 前缀 icon-
![image](https://github.com/Jevon617/unplugin-svg-component/assets/168751396/dc664d2c-e942-4625-bdf8-b66467a0d8b3)
无法显示。
![image](https://github.com/Jevon617/unplugin-svg-component/assets/168751396/ae230302-29e0-4ab6-a733-c3ee22a89644)

**Comment by OneYonder** [comment]
<svg-icon  name="check" />正常显示，加了  <svg-icon  name="icon-check" />无法显示。

**Comment by Jevon617** [comment]
@OneYonder 可以提供一个最小的复现demo吗, 我本地是没有问题的.

**Comment by OneYonder** [comment]
我在别的地方重新下载依赖后变成好的了，可能是编辑器缓存问题
