### ISSUE TITLE
not provide an export named 'default'

### ISSUE THREAD

**Issue by 2815261401** [Jevon617/unplugin-svg-component#22]
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/7592960f-c65e-48a8-9c2d-663c8b10e95d)
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/4b275a7e-d5a3-4879-ad82-58dd5072e9e4)
热更新后,页面刷新有时候会出现该报错
import * as SvgIcon from '~virtual/svg-component';
console.log(SvgIcon)
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/8dd10cba-ecbc-431a-952e-e660cfef0453)

**Comment by 2815261401** [comment]
重新保存vite.config.ts会暂时正常,改完代码只有刷新页面仍会出现该报错

**Comment by Jevon617** [comment]
@2815261401 感谢反馈, 可以提供一个复现的demo吗, 我目前是复现不了的.

**Comment by 2815261401** [comment]
我新建项目后没有发现该问题,应该是缓存文件导致的

**Comment by 2815261401** [comment]
我发现我当前的项目有概率变成这样
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/9a0cb1fd-82d8-4244-9bbd-b560bcff78d8)
出现上面这张图的时间戳就会报  not provide an export named 'default'
这样才是正常的
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/d33507d1-dbd6-4064-88d6-4c173251ab3b)
可能是我项目的内容多,编辑多次后就会带上时间戳,这里我需要怎么改动

**Comment by 2815261401** [comment]
基本上涉及文件变动就会报错

**Comment by Jevon617** [comment]
@2815261401 很奇怪这个模块会被加上时间戳...

**Comment by Jevon617** [comment]
@2815261401 最新版本url匹配的时候去掉了search, 解决了这个bug.

**Comment by 2815261401** [comment]
我部分页面引入了5,6个class,保存的频繁会带上时间戳,可能是编译速度没有跟上运行速度,看看能不能搞个缓存文件放到node_modules\.vite\deps里面

**Comment by 2815261401** [comment]
不过我使用replaceHtml模式也有这个问题,项目文件少的时候就没有

**Comment by 2815261401** [comment]
出现了新的路径错误,和之前应该是同一类型
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/142c7379-0c86-421f-a111-457c5dd4889b)
由于是SSR,我不知道怎么使用调试插件
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/34b6a867-0329-428f-87e5-e5ce58ab4fd5)

**Comment by Jevon617** [comment]
@2815261401 还是需要提供一个复现的demo, 去定位bug的源头.

**Comment by 2815261401** [comment]
由于项目模块比较多,又是ssr,我不太好提供demo,不过我找到了错误的位置
这个是正常的引入
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/88aff28d-1660-429e-9287-0294694abdd8)
这里是报错时的引入
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/d880c487-291b-4b10-bce8-22a273830bd6)
报错只会在文件文件比较多或频繁保存才会触发,同样多了时间戳

**Comment by Jevon617** [comment]
@2815261401 你可以试试把 chunk-3EPHDHJP.js 中的 579 行 `{ ssr: false }` 改成 `{ssr: true}`

![image](https://github.com/Jevon617/unplugin-svg-component/assets/25676701/08f888b2-328c-4928-8448-d250f9f85399)
![image](https://github.com/Jevon617/unplugin-svg-component/assets/25676701/a52b9cdd-70c8-4fd1-b819-e1095856a4d7)

**Comment by 2815261401** [comment]
出现了新的错误
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/602a05a3-b684-4383-8340-7a3bc190d282)

**Comment by 2815261401** [comment]
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/ab2a552b-55d6-435a-b441-0d957eddfc2d)

**Comment by 2815261401** [comment]
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/65a3b00d-decf-4d7a-89e5-4e02de6dc26c)
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/611bc1c2-4407-4b1a-9072-418e11be653a)
这个值不能为空

**Comment by 2815261401** [comment]
是不是vite编译的问题,这个错误只有在编辑引入的函数后才会出现

**Comment by Jevon617** [comment]
@2815261401 
![image](https://github.com/Jevon617/unplugin-svg-component/assets/25676701/7d2c9d99-2df3-4ef4-888f-e0de756ae0ae)
改成这样, ssr为true的时候 , importAnalysisTransform返回的结果 结构不一样了

**Comment by 2815261401** [comment]
![image](https://github.com/Jevon617/unplugin-svg-component/assets/71112636/024d8cb7-1891-4569-9c3e-e3af40ea9765)
我尝试找这个错误的位置,没有找到

**Comment by Jevon617** [comment]
我自己试试ssr, 看看能不能复现吧

**Comment by 2815261401** [comment]
需要在vue里面使用请求才会触发

**Comment by Jevon617** [comment]
可以的话就最好了, 我自己试ssr也没问题.

**Comment by 2815261401** [comment]
https://github.com/2815261401/vite-project
启动 dev,dev2,之后找到一个ts文件,我用的是main.ts,多保存几次就会出错误

**Comment by 2815261401** [comment]
有什么发型吗

**Comment by Jevon617** [comment]
@2815261401 在最新版本解决了

**Comment by 2815261401** [comment]
没有问题了
