### ISSUE TITLE
React/Vite - Tree-shaking not working, all svg in iconDir are included, even if none used

### ISSUE THREAD

**Issue by TeChn4K** [Jevon617/unplugin-svg-component#24]
Hi,

Tree shaking is not working for me. All SVGs in the `iconDir` directory are included, even if none are actually used in the codebase.

vite.config.js
```js
defineConfig({
  plugins: [
    react(),
    unpluginSvgComponent({
      iconDir: path.resolve(__dirname,'./path/to/svgs'),
      dts: true,
      dtsDir: path.resolve(__dirname, './src/types'),
      projectType: 'react',
      treeShaking: true,
    }),
...
```

Then I don't use `import SvgIcon from '~virtual/svg-component'` at all, but all SVGs are included in the sprite

Am i missing something?

---

Edit for futur readers: tree-shaking is only enabled at build time, not in dev mode.

**Comment by Jevon617** [comment]
@TeChn4K Maybe you can set `scanStrategy` to `'text'`

**Comment by TeChn4K** [comment]
Unfortunately the `scanStrategy: 'text'` option didn't help 

I made a demo codesandbox for you [here](https://codesandbox.io/p/devbox/vite-react-ts-forked-jzxxyk?workspaceId=151e8f5d-1663-4f84-97d1-937f0f32fe47&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxbiiqni00072069409su5jo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxbiiqni00022069qayqxu28%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxbiiqni00042069jbyv6cju%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxbiiqni00062069q5x5wxar%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B66.85533295615902%252C33.14466704384098%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxbiiqni00022069qayqxu28%2522%253A%257B%2522id%2522%253A%2522clxbiiqni00022069qayqxu28%2522%252C%2522activeTabId%2522%253A%2522clxbj1ef901d020698c0ny1bh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbiiqnh00012069filavlpb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clxbj1ef901d020698c0ny1bh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxbiiqni00062069q5x5wxar%2522%253A%257B%2522id%2522%253A%2522clxbiiqni00062069q5x5wxar%2522%252C%2522activeTabId%2522%253A%2522clxbj1b7z01bb2069eedyvrwi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxbj1b7z01bb2069eedyvrwi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxbiiqni00042069jbyv6cju%2522%253A%257B%2522id%2522%253A%2522clxbiiqni00042069jbyv6cju%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbiiqni000320691vmbuhji%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxbiiqni000320691vmbuhji%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A25.342261904761898%257D)

You can see that the `svgs` folder contains two files : alarm & album
Only the alarm icon is used in `App.tsx`
But the sprite contains the two icons

**Comment by Jevon617** [comment]
![image](https://github.com/Jevon617/unplugin-svg-component/assets/25676701/aec9c91d-367b-4a14-8ced-dfd110c4b940)

Tree shaking only works on the build mode, and it works correctly. In my understanding, tree shaking in dev mode is meaningless.

**Comment by TeChn4K** [comment]
Sorry, I thought it was also done in dev mode, thanks for the clarification.

In my use case, it is not so meaningless. Ideally, I would like to point `iconDir` to `node_modules/@material-symbols/svg` which contains several thousand icons. My laptop is literally burning with all these icons in the DOM.

Do you think it can be doable to enable tree-shaking in dev mode?

**Comment by Jevon617** [comment]
The tree shaking uses regex to match the icon name, so it is slow, it is impossible to enable it in dev mode.

I think [unplugin-icons](https://github.com/unplugin/unplugin-icons) is better suited for your use case, which imports icons for 

demand.

**Comment by TeChn4K** [comment]
Too bad! Because unplugin-icons is a good tool but it does not handle svg sprite.
Thanks for your time.
