### ISSUE TITLE
获取所有图标

### ISSUE THREAD

**Issue by fan1chun** [Jevon617/unplugin-svg-component#27]
我之前使用 https://github.com/vbenjs/vite-plugin-svg-icons/tree/main#readme

因为他的项目不维护了，现在改用 unplugin-svg-component

之前的项目 使用下面的方法获取所有图标，也是他的插件自带功能，现在要如何替换
import { localIconsName } from '~virtual/svg-component'
export function getLocalIconNames() {
    return localIconsName
}

**Comment by Jevon617** [comment]
![image](https://github.com/user-attachments/assets/10a3a975-2f07-49c8-849a-577679169f42)

**Comment by fan1chun** [comment]
可以了，开始没注意小字

 我main.ts中 import SvgIcon from '~virtual/svg-component' 会TS警告

tsconfig.json 文件已经添加了
{
  "include": ["svg-component.d.ts", "svg-component-global.d.ts"]
}

**Comment by fan1chun** [comment]
import SvgIcon from '~virtual/svg-component' 没有问题，重启编辑器正常了

我npm run dev 图标正常显示
我打包npm run build

图标就不显示了，treeShaking: true  无论true 或 false 打包都不显示
UnpluginSvgComponent({
            vueVersion: 3,
            iconDir: [fileURLToPath(new URL('./src/assets/icons', import.meta.url))],
            prefix: 'local-icon',
            treeShaking: true
        }),

**Comment by fan1chun** [comment]
<SvgIcon :name="name" :style="styles" />  我是这样使用的

**Comment by Jevon617** [comment]
可以提供一个最小的复现demo吗

**Comment by fan1chun** [comment]
可能缓存问题，我现在设置treeShaking: false  打包可以显示。  目前已经调试正常，感谢帮助

**Comment by Jevon617** [comment]
OK
