### ISSUE TITLE
生产环境所有的图标都不展示

### ISSUE THREAD

**Issue by heavenly-zy** [Jevon617/unplugin-svg-component#30]
1. 复现 demo：https://github.com/heavenly-zy/v3-admin-vite/tree/feat/svg-icons
2. 复现步骤：先执行 `pnpm build`，再执行 `pnpm preview` 
![image](https://github.com/user-attachments/assets/6793f4c4-3b16-43e8-8d28-df6fa93abfb0)
如图，生产环境下没有生成任何 svg 图标，开发环境是正常的，另外关闭 tree-shaking 后也正常了，只能通过强制关闭 tree-shaking 才能在生产环境下正常显示吗？

**Comment by Jevon617** [comment]
这里实现 tree-shaking 比较粗暴, 直接扫描文件, 文字匹配 name 是否相同, 但你在中间加了一层封装, 为了使用的时候可以不用 icon 这个前缀, 所以导致匹配不上, 导致所有图标被摇掉了, 这种情况的话可以自定义扫描策略, 可以看看 scanStrategy 这个属性的详细说明.

**Comment by Jevon617** [comment]
@heavenly-zy 另外, 按我的理解, 你是可以不用做这个封装的, 可以在配置里忽略前缀的配置, 自定义组件的样式.

**Comment by heavenly-zy** [comment]
> @heavenly-zy 另外, 按我的理解, 你是可以不用做这个封装的, 可以在配置里忽略前缀的配置, 自定义组件的样式.

我之所以做这个封装，其实就是想在使用时不用加前缀，但是生成 symbolId 时能够自动加上前缀，在配置里忽略前缀其实就与我的初衷不符了；另外 `componentStyle` 内只能写内联样式字符串，样式如果比较多的话感觉不太友好，能否提供一个自定义组件类名的参数，比如 `componentClass`？

**Comment by Jevon617** [comment]
> > @heavenly-zy 另外, 按我的理解, 你是可以不用做这个封装的, 可以在配置里忽略前缀的配置, 自定义组件的样式.
> 
> 我之所以做这个封装，其实就是想在使用时不用加前缀，但是生成 symbolId 时能够自动加上前缀，在配置里忽略前缀其实就与我的初衷不符了；另外 `componentStyle` 内只能写内联样式字符串，样式如果比较多的话感觉不太友好，能否提供一个自定义组件类名的参数，比如 `componentClass`？

`componentClass` 是个不错的想法, 我会加的.

**Comment by Jevon617** [comment]
@heavenly-zy 最新版本0.11.0 已增加 `componentClass `.
