### ISSUE TITLE
当修改 svg 文件热更新生效后手动刷新浏览器，此时页面上的 icon 将变成热更新前的缓存

### ISSUE THREAD

**Issue by pany-ang** [Jevon617/unplugin-svg-component#33]
- 在 0.12.0 版本中可复现
- 在 0.10.4 版本中没有该问题

**Comment by Jevon617** [comment]
v0.12.1 修复了这个 bug, 并且在热更新禁止的时候, 刷新浏览器后会是最新的 icon , 感谢你的反馈!
